"""OpenAPI plugin generator — Phase 2 deliverable.

The generator parses an OpenAPI specification and produces a stub
plugin: a Python file with the plugin class, a metadata block, and
one method per operation. The user then fills in request shaping
and response parsing.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from apiforge.core.client import APIForge as APIForge


class OpenAPIGenerator(ABC):
    """Abstract base for OpenAPI → plugin generators.

    Subclasses implement :meth:`generate` to take an OpenAPI document
    and return a string of Python source code. The CLI in Phase 2 will
    subclass this with a real parser (likely ``openapi-spec-validator``
    + ``prance``).
    """

    @abstractmethod
    def generate(
        self,
        spec: dict[str, Any] | str | Path,
        *,
        plugin_name: str | None = None,
    ) -> str:
        """Render a plugin module as a string."""
        raise NotImplementedError

    @abstractmethod
    def supported_versions(self) -> list[str]:
        """OpenAPI versions this generator understands (e.g. ``["3.0.3", "3.1.0"]``)."""
        raise NotImplementedError


class StubOpenAPIGenerator(OpenAPIGenerator):
    """Reference implementation that returns a TODO skeleton.

    Useful for tests and for users who want to see the expected
    output format before Phase 2 lands. The real generator is a TODO.
    """

    def generate(
        self,
        spec: dict[str, Any] | str | Path,
        *,
        plugin_name: str | None = None,
    ) -> str:
        name = plugin_name or "generated"
        return (
            f'"""{name} — generated by APIForge."""\n'
            "\n"
            "from apiforge.plugins.base import BasePlugin\n"
            "from apiforge.core.metadata import AuthType, OperationMetadata, PluginMetadata\n"
            "\n"
            "\n"
            f"class {name.capitalize()}Plugin(BasePlugin):\n"
            "    metadata = PluginMetadata(\n"
            f"        name={name!r},\n"
            '        version="0.1.0",\n'
            '        description="TODO: generated from OpenAPI spec.",\n'
            "        auth_type=AuthType.TOKEN,\n"
            "    )\n"
            "\n"
            "    async def setup(self) -> None:\n"
            "        return None\n"
        )

    def supported_versions(self) -> list[str]:
        return ["3.0.3", "3.1.0"]
